/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RestaurantApp;

import java.awt.event.ActionEvent;
import java.io.IOException;
import javax.swing.JOptionPane;

        
/**
 *
 * @author ASUS
 */
public class FormRestaurant extends javax.swing.JFrame {

    /**
     * Creates new form FormRestaurant
     */
    public FormRestaurant() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JInternalFrame();
        UpperTitle = new javax.swing.JLabel();
        CustomerDataPanel = new javax.swing.JPanel();
        Name = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        PhoneNumber = new javax.swing.JTextField();
        LabelNama = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        SteakCheckBox = new javax.swing.JCheckBox();
        SphagettiCheckBox = new javax.swing.JCheckBox();
        PizzaCheckBox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        OrderButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Bill = new javax.swing.JTextArea();
        TotalBox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Pemesanan Makanan");

        Header.setTitle("Aplikasi Pemesanan Makanan");
        Header.setVisible(true);

        UpperTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UpperTitle.setText("Aplikasi Pemesanan");

        CustomerDataPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        LabelNama.setText("Nama");

        jLabel1.setText("Alamat");

        jLabel2.setText("Nomor HP");

        jLabel3.setText("Data Pembeli");

        javax.swing.GroupLayout CustomerDataPanelLayout = new javax.swing.GroupLayout(CustomerDataPanel);
        CustomerDataPanel.setLayout(CustomerDataPanelLayout);
        CustomerDataPanelLayout.setHorizontalGroup(
            CustomerDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CustomerDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomerDataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 89, Short.MAX_VALUE))
                    .addGroup(CustomerDataPanelLayout.createSequentialGroup()
                        .addGroup(CustomerDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CustomerDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Address)
                            .addComponent(PhoneNumber)
                            .addComponent(Name, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        CustomerDataPanelLayout.setVerticalGroup(
            CustomerDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(CustomerDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNama))
                .addGap(18, 18, 18)
                .addGroup(CustomerDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(CustomerDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        MenuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SteakCheckBox.setText("Steak");
        SteakCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SteakCheckBoxActionPerformed(evt);
            }
        });

        SphagettiCheckBox.setText("Sphagetti");
        SphagettiCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SphagettiCheckBoxActionPerformed(evt);
            }
        });

        PizzaCheckBox.setText("Pizza");
        PizzaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PizzaCheckBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Pilih Menu");

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PizzaCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SphagettiCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SteakCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(16, 16, 16)
                .addComponent(SteakCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SphagettiCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PizzaCheckBox)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        OrderButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        OrderButton.setText("TAMBAH");
        OrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderButtonActionPerformed(evt);
            }
        });

        Bill.setColumns(20);
        Bill.setRows(5);
        jScrollPane1.setViewportView(Bill);

        TotalBox.setBackground(new java.awt.Color(51, 51, 51));
        TotalBox.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TotalBox.setForeground(new java.awt.Color(255, 255, 51));
        TotalBox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TotalBox.setText("-");
        TotalBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header.getContentPane());
        Header.getContentPane().setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CustomerDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(HeaderLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TotalBox, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(OrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(UpperTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(24, 24, 24))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(UpperTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CustomerDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TotalBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private int total = 0;

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void SteakCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SteakCheckBoxActionPerformed
        // TODO add your handling code here:
         if(SteakCheckBox.isSelected()){
            total += 70000;
        }
        else{
            total -= 70000;
        }
        TotalBox.setText(""+total);
     
    }//GEN-LAST:event_SteakCheckBoxActionPerformed

    private void SphagettiCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SphagettiCheckBoxActionPerformed
        // TODO add your handling code here:
            if(SphagettiCheckBox.isSelected()){
            total += 60000;
        }
        else{
            total -= 60000;
        }
        TotalBox.setText(""+total);
    }//GEN-LAST:event_SphagettiCheckBoxActionPerformed
      
    private void TotalBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalBoxActionPerformed
        // TODO add your handling code here:
        getTotal();
    }//GEN-LAST:event_TotalBoxActionPerformed
            public String OrderBill = "";
    private void OrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderButtonActionPerformed
        // TODO add your handling code here:
       
        getTotal();
        OrderBill += "Nama : " + Name.getText() +"\n";
        OrderBill += "Alamat : " + Address.getText() +"\n";
        OrderBill += "Telp :" + PhoneNumber.getText() +"\n";
        OrderBill +="-------------------------------------\n";
        OrderBill += "Pesanan :\n";
        if(SteakCheckBox.isSelected())
        {
            OrderBill +="  - " + SteakCheckBox.getText() + "         (70000)\n";
        }
        if(SphagettiCheckBox.isSelected())
        {
            OrderBill +="  - " + SphagettiCheckBox.getText() + "   (60000)\n";
        }
        if(PizzaCheckBox.isSelected())
        {
            OrderBill +="  - " + PizzaCheckBox.getText() + "         (85000)\n";
        }
        OrderBill +="-------------------------------------\n";
        OrderBill +="Total Bayar  :\n";
        OrderBill +="                Rp.  " + TotalBox.getText() +"\n";
        OrderBill +="------------------------------------\n";
        OrderBill +="\n\n";
        Bill.setText(OrderBill);
    }//GEN-LAST:event_OrderButtonActionPerformed

    private void PizzaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PizzaCheckBoxActionPerformed
        // TODO add your handling code here:
           if(PizzaCheckBox.isSelected()){
            total += 85000;
        }
        else{
            total -= 85000;
        }
        TotalBox.setText(""+total);
    }//GEN-LAST:event_PizzaCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRestaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRestaurant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextArea Bill;
    private javax.swing.JPanel CustomerDataPanel;
    private javax.swing.JInternalFrame Header;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JTextField Name;
    private javax.swing.JButton OrderButton;
    private javax.swing.JTextField PhoneNumber;
    private javax.swing.JCheckBox PizzaCheckBox;
    private javax.swing.JCheckBox SphagettiCheckBox;
    private javax.swing.JCheckBox SteakCheckBox;
    private javax.swing.JTextField TotalBox;
    private javax.swing.JLabel UpperTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
private void getTotal() {
       int total = 0;
       
       if(SteakCheckBox.isSelected()){
           total += 70000;
       }
       if(SphagettiCheckBox.isSelected()){
           total += 60000;
       }
       if(PizzaCheckBox.isSelected()){
           total += 85000;
       }
       TotalBox.setText(Integer.toString(total));
    }
}
